PERTURBATIONS = {
    "shuffle_control_en": {
        "perturbation_function": partial(perturb_shuffle_deterministic, lang='EN', seed=None, shuffle=False),
        "lang": 'en',
        "affect_function": affect_shuffle,
        "filter_function": filter_shuffle,
        "gpt2_tokenizer": TOKENIZATIONER['EN']['shuffle'],
        "color": "#606060",
    },
    "shuffle_control_fr": {
    "perturbation_function": partial(perturb_shuffle_deterministic, lang='FR', seed=None, shuffle=False),
    "lang": 'fr',
    "affect_function": affect_shuffle,
    "filter_function": filter_shuffle,
    "gpt2_tokenizer": TOKENIZATIONER['FR']['shuffle'],
    "color": "#606060",
                                                            },
    "shuffle_control_de": {
        "perturbation_function": partial(perturb_shuffle_deterministic, lang='DE', seed=None, shuffle=False),
        "lang": 'de',
        "affect_function": affect_shuffle,
        "filter_function": filter_shuffle,
        "gpt2_tokenizer": TOKENIZATIONER['DE']['shuffle'],
        "color": "#606060",
    },
    "shuffle_control_nl": {
        "perturbation_function": partial(perturb_shuffle_deterministic, lang='NL', seed=None, shuffle=False),
        "lang": 'nl',
        "affect_function": affect_shuffle,
        "filter_function": filter_shuffle,
        "gpt2_tokenizer": TOKENIZATIONER['NL']['shuffle'],
        "color": "#606060",
        },
    "shuffle_control_it": {
        "perturbation_function": partial(perturb_shuffle_deterministic, lang='IT', seed=None, shuffle=False),
         "lang": 'it',
         "affect_function": affect_shuffle,
        "filter_function": filter_shuffle,
        "gpt2_tokenizer": TOKENIZATIONER['IT']['shuffle'],
         "color": "#606060",
                },
    "shuffle_control_tr": {
        "perturbation_function": partial(perturb_shuffle_deterministic, lang='TR', seed=None, shuffle=False),
        "lang": 'tr',
        "affect_function": affect_shuffle,
        "filter_function": filter_shuffle,
        "gpt2_tokenizer": TOKENIZATIONER['TR']['shuffle'],
        "color": "#606060",
    },
    "shuffle_control_zh": {
        "perturbation_function": partial(perturb_shuffle_deterministic, lang='ZH', seed=None, shuffle=False),
        "lang": 'zh',
        "affect_function": affect_shuffle,
        "filter_function": filter_shuffle,
        "gpt2_tokenizer": TOKENIZATIONER['ZH']['shuffle'],
        "color": "#606060",
    },
    "shuffle_control_ro": {
        "perturbation_function": partial(perturb_shuffle_deterministic, lang='RO', seed=None, shuffle=False),
        "lang": 'ro',
        "affect_function": affect_shuffle,
        "filter_function": filter_shuffle,
        "gpt2_tokenizer": TOKENIZATIONER['RO']['shuffle'],
        "color": "#606060",
    },
    "shuffle_control_ru": {
        "perturbation_function": partial(perturb_shuffle_deterministic, lang='RU', seed=None, shuffle=False),
        "lang": 'ru',
        "affect_function": affect_shuffle,
        "filter_function": filter_shuffle,
        "gpt2_tokenizer": TOKENIZATIONER['RU']['shuffle'],
        "color": "#606060",
    },
    "shuffle_local3_en": {
        "perturbation_function": partial(perturb_shuffle_local, lang='EN', seed=0, window=3),
        "affect_function": affect_shuffle,
        "filter_function": filter_shuffle,
        "gpt2_tokenizer": TOKENIZATIONER['EN']['shuffle'],
        "color": "#208EA3",
    },
    "shuffle_nondeterministic_en": {
        "perturbation_function": partial(perturb_shuffle_nondeterministic, lang='EN', rng=default_rng(0)),
        "affect_function": affect_shuffle,
        "filter_function": filter_shuffle,
        "gpt2_tokenizer": TOKENIZATIONER['EN']['shuffle'],
        "color": "#E8384F",
    },
    "shuffle_nondeterministic_tr": {
        "perturbation_function": partial(perturb_shuffle_nondeterministic, lang='TR', rng=default_rng(0)),
        "affect_function": affect_shuffle,
        "filter_function": filter_shuffle,
        "gpt2_tokenizer": TOKENIZATIONER['TR']['shuffle'],
        "color": "#E8384F",
    },
    "shuffle_nondeterministic_tr": {
        "perturbation_function": partial(perturb_shuffle_nondeterministic, lang='TR', rng=default_rng(0)),
        "affect_function": affect_shuffle,
        "filter_function": filter_shuffle,
        "gpt2_tokenizer": TOKENIZATIONER['TR']['shuffle'],
            "color": "#E8384F",
                },
    "shuffle_deterministic21_en": {
        "perturbation_function": partial(perturb_shuffle_deterministic, lang='EN', seed=21, shuffle=True),
        "affect_function": affect_shuffle,
        "filter_function": filter_shuffle,
        "gpt2_tokenizer": TOKENIZATIONER['EN']['shuffle'],
        "color": "#FFB000",
    },
    "shuffle_deterministic21_tr": {
        "perturbation_function": partial(perturb_shuffle_deterministic, lang='TR', seed=21, shuffle=True),
        "affect_function": affect_shuffle,
        "filter_function": filter_shuffle,
        "gpt2_tokenizer": TOKENIZATIONER['TR']['shuffle'],
         "color": "#FFB000",
    },

    "shuffle_deterministic57_en": {
        "perturbation_function": partial(perturb_shuffle_deterministic, lang='EN',seed=57, shuffle=True),
        "affect_function": affect_shuffle,
        "filter_function": filter_shuffle,
        "gpt2_tokenizer":TOKENIZATIONER['EN']['shuffle'],
        "color": "#8db000",
    },
    "shuffle_deterministic84_en": {
        "perturbation_function": partial(perturb_shuffle_deterministic, lang='EN',seed=84, shuffle=True),
        "affect_function": affect_shuffle,
        "filter_function": filter_shuffle,
        "gpt2_tokenizer": TOKENIZATIONER['EN']['shuffle'],
        "color": "#62BB35",
    },

    "shuffle_deterministic57_tr": {
        "perturbation_function": partial(perturb_shuffle_deterministic, lang='TR',seed=57, shuffle=True),
        "affect_function": affect_shuffle,
        "filter_function": filter_shuffle,
        "gpt2_tokenizer":TOKENIZATIONER['TR']['shuffle'],
        "color": "#8db000",
                                                          },

      "shuffle_deterministic21_word_tr": {
        "perturbation_function": partial(perturb_shuffle_deterministic_word, lang='TR',seed=21, shuffle=True),
        "affect_function": affect_shuffle,
        "filter_function": filter_shuffle,
        "gpt2_tokenizer":TOKENIZATIONER['TR']['shuffle'],
        "color": "#8db000",
                                                          },
     "shuffle_deterministic84_tr": {
        "perturbation_function": partial(perturb_shuffle_deterministic, lang='TR',seed=84, shuffle=True),
        "affect_function": affect_shuffle,
        "filter_function": filter_shuffle,
        "gpt2_tokenizer": TOKENIZATIONER['TR']['shuffle'],
            "color": "#62BB35",
                                                              },
    "shuffle_local5_en": {
        "perturbation_function": partial(perturb_shuffle_local, lang='EN',seed=0, window=5),
        "affect_function": affect_shuffle,
        "filter_function": filter_shuffle,
        "gpt2_tokenizer":TOKENIZATIONER['EN']['shuffle'],
        "color": "#4178BC",
    },
    "shuffle_local10_en": {
        "perturbation_function": partial(perturb_shuffle_local, lang='EN',seed=0, window=10),
        "affect_function": affect_shuffle,
        "filter_function": filter_shuffle,
        "gpt2_tokenizer": TOKENIZATIONER['EN']['shuffle'],
        "color": "#AA71FF",
    },
    "shuffle_even_odd_en": {
        "perturbation_function": partial(perturb_shuffle_even_odd, lang='EN'),
        "affect_function": affect_shuffle,
        "filter_function": filter_shuffle,
        "gpt2_tokenizer": TOKENIZATIONER['EN']['shuffle'],
        "color": "#E37CFF",
    },

    "shuffle_local5_tr": {
        "perturbation_function": partial(perturb_shuffle_local, lang='TR',seed=0, window=5),
        "affect_function": affect_shuffle,
        "filter_function": filter_shuffle,
        "gpt2_tokenizer":TOKENIZATIONER['TR']['shuffle'],
         "color": "#4178BC",
                                                            },
    "shuffle_local10_tr": {
        "perturbation_function": partial(perturb_shuffle_local, lang='TR',seed=0, window=10),
         "affect_function": affect_shuffle,
         "filter_function": filter_shuffle,
        "gpt2_tokenizer": TOKENIZATIONER['TR']['shuffle'],
         "color": "#AA71FF",
                             },
        "shuffle_even_odd_tr": {
        "perturbation_function": partial(perturb_shuffle_even_odd, lang='TR'),
        "affect_function": affect_shuffle,
         "filter_function": filter_shuffle,
        "gpt2_tokenizer": TOKENIZATIONER['TR']['shuffle'],
        "color": "#E37CFF",},

        "shuffle_local3_tr": {
        "perturbation_function": partial(perturb_shuffle_local, lang='TR',seed=0, window=3),
         "affect_function": affect_shuffle,
        "filter_function": filter_shuffle,
          "gpt2_tokenizer":TOKENIZATIONER['TR']['shuffle'],
         "color": "#4178BC",},

        "shuffle_local3_word_tr": {
         "perturbation_function": partial(perturb_shuffle_local_word, lang='TR',seed=0, window=3),
         "affect_function": affect_shuffle,
         "filter_function": filter_shuffle,
        "gpt2_tokenizer":TOKENIZATIONER['TR']['shuffle'],
         "color": "#4178BC",},

}